### PR TITLE
Refine Source|Buffer.indexOf(ByteBuffer) contracts

### LINKED ISSUE #422: Buffer.indexOf(ByteString) accepts negative indices
While `Source.indexOf(ByteString)` throws `IllegalArgumentException` on attempts to supply negative indices, `Buffer`'s overload accepts them and return some results.

Expected behavior: `Buffer.indexOf(ByteString(...), -1)` should throw IAE.

### PR DESCRIPTION
**Pull request by fzhinkin**
Closes #422

### CODE REVIEW

File: core/common/src/ByteStrings.kt [hunk 1]
```diff
@@ -85,6 +85,8 @@ public fun Source.readByteString(byteCount: Int): ByteString {
  * expands the source's buffer as necessary until [byteString] is found. This reads an unbounded number of
  * bytes into the buffer. Returns `-1` if the stream is exhausted before the requested bytes are found.
  *
+ * For empty byte strings this function always return `0`.
```
Comment (fzhinkin) [inline core/common/src/ByteStrings.kt:88]: See #423. I'm not sure how to handle empty byte strings yet.

Comment (shanshin) [reply core/common/src/ByteStrings.kt:88]: It seems to me that this is really better than fetching the data, provided that we always ignore what has been fetched.

Maybe it should be explicitly written that in the case of an empty byte string, the data will never be read from the source?

Comment (fzhinkin) [reply core/common/src/ByteStrings.kt:88]: > Maybe it should be explicitly written that in the case of an empty byte string, the data will never be read from the source?

Then, it would be inconsistent with the `Buffer`'s "overload". These two functions already behave differently, but I'd like to keep them as close to each other as possible.

File: core/common/src/ByteStrings.kt [hunk 2]
```diff
@@ -117,11 +117,24 @@ public fun Source.indexOf(byteString: ByteString, startIndex: Long = 0): Long {
...
+/**
+ * Returns the index of the first match for [byteString] in the buffer at or after [startIndex].
+ * Returns `-1` if the stream is exhausted before the requested bytes are found.
+ *
+ * For empty byte strings this function always return `0`.
+ *
+ * @param byteString the sequence of bytes to find within the buffer.
+ * @param startIndex the index into the buffer to start searching from.
+ *
+ * @throws IllegalArgumentException if [startIndex] is negative or if it is greater of equal to buffer's [Buffer.size].
```
Comment (fzhinkin) [inline core/common/src/ByteStrings.kt:129]: BTW, this behavior is also inconsistent with `CharSequence.indexOf`, which I'm considering maybe not as a paragon, but as something to be aligned with.

**Review by shanshin — APPROVED** [review]
