### PR TITLE
Fix potential UB in ByteString.hashCode

### LINKED ISSUE #190: Possible UB in ByteString hash function
The ByteString hash function [caches previously calculated values](https://github.com/Kotlin/kotlinx-io/blob/1ee0a1df3673e9f610cdc4fd820344b5bc6851b7/bytestring/common/src/ByteString.kt#L107-L117). The member variable that stores the cached value is a [non-atomic `Int`](https://github.com/Kotlin/kotlinx-io/blob/1ee0a1df3673e9f610cdc4fd820344b5bc6851b7/bytestring/common/src/ByteString.kt#L72). 

I believe that kotlinx-ios hash cache logic was inspired by the [google protobuf ByteString hash implementation](https://github.com/protocolbuffers/protobuf/blob/main/java/core/src/main/java/com/google/protobuf/ByteString.java#L981-L999). But that hash caching has a disclaimer that the [non-atomic `Int` backing the cache is safe because of JVM memory model semantics](https://github.com/protocolbuffers/protobuf/blob/main/java/core/src/main/java/com/google/protobuf/ByteString.java#L139-L144). 

Is it safe to use a non-atomic `Int` for Kotlin native builds? Does the hash cache member variable need to be converted to an `Atomic<Int>` for non-JVM platforms?

### PR DESCRIPTION
**Pull request by qwwdfsad**
It has a benign JVM data-race on the hashCode field, but on K/N LLVM has no guarantees it will read default or written value (e.g. OoTA is one of the possibilities). The recommendation from K/N folks is to use @Volatile here

Fixes #190

### CODE REVIEW

**Comment by fzhinkin** [comment]
>  OoTA is one of the possibilities

I thought it shouldn't, but:
> If there is a race on a given memory location, loads from that location return **undef**.

https://llvm.org/docs/Atomics.html#notatomic

File: bytestring/common/src/ByteString.kt [hunk 1]
```diff
@@ -69,6 +70,7 @@ public class ByteString private constructor(
     public constructor(data: ByteArray, startIndex: Int = 0, endIndex: Int = data.size) :
             this(data.copyOfRange(startIndex, endIndex), null)
 
+    @Volatile
```
Comment (fzhinkin) [inline bytestring/common/src/ByteString.kt:73]: Does it make sense to add an expect annotation like `VolatileInNative` and actualize it with `Volatile` only in native?

Like in [this patch](https://gist.github.com/fzhinkin/5cd4a5af93c6c6611ed7d8f405a55fa7)

Comment (fzhinkin) [reply bytestring/common/src/ByteString.kt:73]: The nicest alternative would be to somehow perform load/store w/ relaxed memory ordering, though:
https://godbolt.org/z/rEdcobsW3

File: bytestring/common/src/-Platform.kt [hunk 2]
```diff
@@ -0,0 +1,14 @@
+/*
+* Copyright 2010-2023 JetBrains s.r.o. and Kotlin Programming Language contributors.
+* Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE.txt file.
+*/
+package kotlinx.io.bytestring
+
+/**
+ * Annotation indicating that the marked property is the subjectof benign data race.
```
Comment (fzhinkin) [inline bytestring/common/src/-Platform.kt:8]:
```suggestion
 * Annotation indicating that the marked property is the subject of benign data race.
```

**Review by fzhinkin — APPROVED** [review]
Besides the small typo, everything LGTM. Thanks for resolving the issue!
